// <auto-generated />
using System;
using Health_Guardian_AI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health_Guardian_AI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618052542_AddInFormPredictionsTable")]
    partial class AddInFormPredictionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Health_Guardian_AI.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.HealthProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<double>("AvgGlucose")
                        .HasColumnType("float");

                    b.Property<double>("BMI")
                        .HasColumnType("float");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmokingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.InFormPrediction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HPId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Messenge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HPId")
                        .IsUnique();

                    b.ToTable("InFormPredictions");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.Prediction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Factors_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factors_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HPId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Probability")
                        .HasColumnType("float");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HPId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.UserMemory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemoryContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMemories");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.ChatMessage", b =>
                {
                    b.HasOne("Health_Guardian_AI.Models.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.HealthProfile", b =>
                {
                    b.HasOne("Health_Guardian_AI.Models.User", "User")
                        .WithMany("HealthProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.InFormPrediction", b =>
                {
                    b.HasOne("Health_Guardian_AI.Models.HealthProfile", "HealthProfile")
                        .WithOne("InFormPrediction")
                        .HasForeignKey("Health_Guardian_AI.Models.InFormPrediction", "HPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.Prediction", b =>
                {
                    b.HasOne("Health_Guardian_AI.Models.HealthProfile", "HealthProfile")
                        .WithOne("Prediction")
                        .HasForeignKey("Health_Guardian_AI.Models.Prediction", "HPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.UserMemory", b =>
                {
                    b.HasOne("Health_Guardian_AI.Models.User", "User")
                        .WithMany("UserMemories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.HealthProfile", b =>
                {
                    b.Navigation("InFormPrediction")
                        .IsRequired();

                    b.Navigation("Prediction")
                        .IsRequired();
                });

            modelBuilder.Entity("Health_Guardian_AI.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("HealthProfiles");

                    b.Navigation("UserMemories");
                });
#pragma warning restore 612, 618
        }
    }
}
